### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by bondarenkorom** [phantomstudios/strapi-plugin-github-publish#24]
Hello! I have an error when running `yarn build` command after enabling this plugin v0.2.0 for Strapi v4.7.1

```
% yarn build
yarn run v1.22.10
$ strapi build
Starting the compilation for TypeScript files in /strapi
Building your admin UI with development configuration...
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:1074:7)
    at /Users/strapi/node_modules/@strapi/admin/utils/create-cache-dir.js:82:33
    at Array.filter (<anonymous>)
    at createCacheDir (/Users/strapi/node_modules/@strapi/admin/utils/create-cache-dir.js:80:6)
    at async Object.build (/Users/strapi/node_modules/@strapi/admin/index.js:27:3)
    at async module.exports (/Users/strapi/node_modules/@strapi/strapi/lib/commands/build.js:12:3) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

<img width="800" alt="Screenshot 2023-03-30 at 14 40 01" src="https://user-images.githubusercontent.com/109078526/228840654-623b349d-2b97-4db6-af4b-2f0c42d581dd.png">

**Comment by Sletheren** [comment]
have the same, did you manage to solve it? @bondarenkorom

**Comment by peckpeck20** [comment]
I get the same error
