### ISSUE TITLE
Status Code 422 When Publishing

### ISSUE THREAD

**Issue by stickchartkeith** [phantomstudios/strapi-plugin-github-publish#8]
Managed to get the configuration working and know that it's talking to my repository (part of a GitHub Organization) - as I had to work through a few 401s (Auth Issues, resolved with Personal Access Token) and 404s (Action / Workflow file name was wrong).

I am however completely stuck now though as when I click the "Publish" button on the GitHub Publishing page, I'm getting a Status Code 422 failure:

`[2021-06-23T02:39:34.698Z] error Error: Request failed with status code 422
    at createError (/home/ubuntu/strapiV2/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/ubuntu/strapiV2/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/ubuntu/strapiV2/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

I have tried this both locally (OS X) and published out on a server (AWS EC2 - Ubuntu 20.04), still getting this error.  Can I get some advice, as I'm not sure where else to look to resolve this?  Thanks!

**Comment by stickchartkeith** [comment]
I finally got around to looking at this, and the issue resulted in how the workflow config file was setup (.yml).  In order for this plug-in to initiate the workflow, I had to ensure the event (on:) was setup as follows ... Basically needed to ensure that you have the ability to manually trigger the workflow.

`on:
  workflow_dispatch:
  repository_dispatch:`

I didn't see this anywhere in the documentation, so wanted to at least post this here in the event someone else ran across this.  Would recommend that this is included in the README for others.

More on GitHub manual workflows: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events

**Comment by bkroeker** [comment]
@stickchartkeith Thanks for this.  I ran into the same problem.

Even after your fix, I was still getting a 422 error.  I additionally needed to remove this section from my strapi config:

```
    inputs: {
      // Optional inputs to pass through to the GitHub workflow
      some_input: 'Some value',
      some_other_input: 'Some other value',
     },
```

I had copied these inputs from the documentation for this plugin.  I wasn't using the values, and assumed they'd just be silently ignored.  Turns out including them was preventing the github action from working.

**Comment by 4F2E4A2E** [comment]
> I finally got around to looking at this, and the issue resulted in how the workflow config file was setup (.yml). In order for this plug-in to initiate the workflow, I had to ensure the event (on:) was setup as follows ... Basically needed to ensure that you have the ability to manually trigger the workflow.
> 
> `on: workflow_dispatch: repository_dispatch:`
> 
> I didn't see this anywhere in the documentation, so wanted to at least post this here in the event someone else ran across this. Would recommend that this is included in the README for others.
> 
> More on GitHub manual workflows: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events

this worked for me, thanks @stickchartkeith
